services:
  backend:
    build:
      context: .
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/credential.json
      GIN_MODE: release
    volumes:
      - $GOOGLE_CREDENTIAL:/etc/gcloud/credential.json
    ports:
      - 8045:8080
    profiles:
      - release

  dev:
    image: golang:${GO_VERSION}
    command: ["go", "run", "."]
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/credential.json
      GOPATH: /go/
      GIN_MODE: debug
    working_dir: "/go/src/github.com/gilkor/ba-version-2/"
    volumes:
      - $GOOGLE_CREDENTIAL:/etc/gcloud/credential.json
      - $GOPATH/pkg:/go/pkg
      - $GOPATH/bin:/go/bin
      - .:/go/src/github.com/gilkor/ba-version-2
    ports:
      - 8034:8080
