services:
  dev: &base
    image: golang:${GO_VERSION}
    command: [ "go", "run", "-tags", "demo,migrate", "./cmd/app" ]
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/credential.json
      GOPATH: /go/
      GIN_MODE: debug
      PG_URL: $PG_URL
      MIGRATION_SRC: file://files/migration
    working_dir: "/go/src/github.com/gilkor/ba-version-2/"
    volumes:
      - $GOOGLE_CREDENTIAL:/etc/gcloud/credential.json
      - $GOPATH/pkg:/go/pkg
      - $GOPATH/bin:/go/bin
      - .:/go/src/github.com/gilkor/ba-version-2
      - $PUBLIC_CLIENT_KEY:/etc/juno/key.rsa.pub
      - ./files/abac_model.conf:/app/casbin/model.conf
    ports:
      - 8034:8080
    depends_on:
      - postgres

  migrate:
    <<: *base
    command: [ "go", "run", "-tags", "migrate", "./cmd/migrate", "0"]
    environment:
      PG_URL: $PG_URL
      MIGRATION_SRC: file://files/migration
      MIGRATION_ONLY: true
    ports: []

  postgres:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'buangin'
    ports:
      - 3432:5432

  rabbitmq:
    image: rabbitmq:3.8.12-management
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build:
      context: .
      args:
        GOPATH: /go/
    image: ba-version-2
    environment:
      PG_URL: $PG_URL
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/credential.json
      GIN_MODE: release
      LOG_LEVEL: warn
      CASBIN_MODEL_FILE: /usr/local/bin/config/model.conf
      MIGRATION_SRC: $MIGRATION_SRC
    ports:
      - 8045:8080
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - $GOOGLE_CREDENTIAL:/etc/gcloud/credential.json
      - ./config/config.yml:/usr/local/bin/config/config.yml
      - $PUBLIC_CLIENT_KEY:/etc/juno/key.rsa.pub
      - ./files/abac_model.conf:/usr/local/bin/config/model.conf

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    image: integration
    depends_on:
      - app

volumes:
  pg-data: