app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'
  auth_key: 'X-App-Token'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'

jwtauth:
  base_url: https://oauth.domain.com/v2
  client_key_file: /etc/jwt-auth/key.rsa.pub

casbin:
  model_file: /app/casbin/model.conf
  load_policy_interval: 60

google:
  project_id: 'gcloud-project-123456'